#!/usr/bin/env bun

/**
 * Generates docs/provider-jurisdictions.md from the jurisdiction table (XCOD-61).
 *
 * The doc is generated rather than hand-written so it cannot drift from the table that actually
 * governs residency enforcement. Wired into script/generate.ts, so CI regenerates and commits it.
 */

import { mkdir } from "fs/promises"
// Relative rather than "@opencode-ai/core/jurisdiction": the root workspace has no dependency
// on core, so the package specifier does not resolve from here.
import { Jurisdiction } from "../packages/core/src/jurisdiction"

const OUT = "docs/provider-jurisdictions.md"

const REGION_LABEL: Record<Jurisdiction.Region, string> = {
  eu: "EU",
  us: "US",
  other: "Non-EU",
  configurable: "Depends on configuration",
  unknown: "Not determinable",
}

const BASIS_LABEL: Record<Jurisdiction.Basis, string> = {
  processing: "Processing location",
  entity: "Legal entity only",
  both: "Entity and processing",
  "user-configured": "Deployment configuration",
  "user-endpoint": "User-supplied endpoint",
  gateway: "Inherited from upstream",
  none: "No claim",
}

function cell(value: string) {
  return value.replaceAll("|", "\\|")
}

function section(title: string, ids: string[]) {
  if (ids.length === 0) return ""
  const rows = ids
    .sort()
    .map((id) => {
      const claim = Jurisdiction.lookup(id)
      const detail = claim.euOption ? `${claim.note}<br><br>**To get EU:** ${claim.euOption}` : claim.note
      return `| \`${id}\` | ${REGION_LABEL[claim.region]} | ${BASIS_LABEL[claim.basis]} | ${cell(detail)} |`
    })
    .join("\n")

  return [
    `## ${title}`,
    "",
    "| Provider | Region | Claim rests on | What is actually true |",
    "| --- | --- | --- | --- |",
    rows,
    "",
    "",
  ].join("\n")
}

const all = Jurisdiction.taggedProviders()
const by = (region: Jurisdiction.Region) => all.filter((id) => Jurisdiction.lookup(id).region === region)

const body = [
  "<!-- Generated by script/jurisdictions.ts. Do not edit by hand; edit packages/core/src/jurisdiction.ts. -->",
  "",
  "# Model provider jurisdictions",
  "",
  "Where each model provider processes your data, and — just as importantly — what that claim actually rests on.",
  "",
  "Lunos itself is self-hosted: it runs on infrastructure you provide, and there is no Lunos-operated service in the data path. The only data that leaves your infrastructure goes to the model provider you configure. This page is about *those* providers.",
  "",
  "## How to read this",
  "",
  'A provider being "EU" can mean two very different things, and conflating them is how sovereignty claims become misleading:',
  "",
  "- **Processing location** — your request data is processed on infrastructure in the EU.",
  "- **Legal entity** — the vendor is an EU-registered company. This says nothing about where data is processed.",
  "",
  "Only providers where **both** hold are listed as EU below. Where a provider rests on just one, the table says which one.",
  "",
  '**"Depends on configuration"** is not a hedge. Hyperscalers such as Azure, AWS Bedrock and Google Vertex can all run in the EU, and all default to a non-EU region. Whether a given deployment is EU-resident is a choice the deployer makes, not a property of the provider — so these are never reported as EU automatically. The residency controls treat them as non-EU unless the deployment demonstrates otherwise.',
  "",
  "**Gateways** (OpenRouter, Vercel AI Gateway, and similar) route onward to other providers. They have no jurisdiction of their own — the effective jurisdiction is whatever they route to, which may vary per request.",
  "",
  "",
  section("EU-resident providers", by("eu")),
  [
    "### Using one of these",
    "",
    "No plugin or extra configuration is needed — these providers ship in the default model catalog. Set the provider's API key and select one of its models:",
    "",
    "```sh",
    "export SCALEWAY_API_KEY=...   # Scaleway (France)",
    "export OVHCLOUD_API_KEY=...   # OVHcloud (France)",
    "export HETZNER_API_KEY=...    # Hetzner (Germany)",
    "export MISTRAL_API_KEY=...    # Mistral (France)",
    "```",
    "",
    "Then list what that provider currently offers and pick a model from it:",
    "",
    "```sh",
    "lunos models scaleway",
    "```",
    "",
    "",
  ].join("\n"),
  section("Depends on your configuration", by("configurable")),
  section("Non-EU providers", [...by("us"), ...by("other")]),
  section("No jurisdiction of their own", by("unknown")),
  "## Scope and limits of this page",
  "",
  "- This records **where data is processed**, not a data-protection assessment. A provider being EU-resident does not by itself discharge GDPR obligations — you still need the appropriate agreement with that provider.",
  "- Sub-processors are not enumerated. A provider processing in the EU may still rely on sub-processors; check its own documentation.",
  "- Entries are maintained on the project's best current understanding and are not a substitute for the provider's own contractual commitments. Where something could not be verified, the table says so rather than guessing.",
  "",
  "Corrections are welcome — the source of truth is `packages/core/src/jurisdiction.ts`, and a correction there regenerates this page.",
  "",
].join("\n")

await mkdir("docs", { recursive: true })
await Bun.write(OUT, body)
console.log(`wrote ${OUT} (${all.length} providers)`)
