#!/usr/bin/env bun

/**
 * Writes the outbound-call table in docs/deployment/self-hosted.md from Offline.CALLS (XCOD-121),
 * so the documented list can't drift from what LUNOS_OFFLINE actually gates. Wired into
 * script/generate.ts. `--check` exits non-zero when the doc is out of date.
 */

// Relative for the same reason as script/jurisdictions.ts: the root workspace doesn't depend on core.
import { Offline } from "../packages/core/src/offline"
import prettier from "prettier"

const FILE = "docs/deployment/self-hosted.md"
const START = "<!-- offline-calls:start (generated by script/offline-calls.ts; do not edit) -->"
const END = "<!-- offline-calls:end -->"

const OFFLINE_LABEL: Record<Offline.Call["offline"], string> = {
  blocked: "**Off**",
  tool: "**Off** (tool not offered)",
  yours: "On: you configured it",
  command: "Only if you run it",
}

function cell(value: string) {
  return value.replaceAll("|", "\\|")
}

export function table() {
  return [
    "| Outbound call | Host(s) | When | With `LUNOS_OFFLINE=1` | Other switch |",
    "| --- | --- | --- | --- | --- |",
    ...Offline.CALLS.map((call) =>
      [call.what, call.hosts, call.when, OFFLINE_LABEL[call.offline], call.alsoOffBy ?? "none"]
        .map(cell)
        .join(" | ")
        .replace(/^/, "| ")
        .concat(" |"),
    ),
  ].join("\n")
}

if (import.meta.main) {
  const text = await Bun.file(FILE).text()
  const start = text.indexOf(START)
  const end = text.indexOf(END)
  if (start === -1 || end === -1) throw new Error(`offline-calls: markers missing in ${FILE}`)
  // Formatted here, not only by script/format.ts, so --check compares like with like.
  const next = await prettier.format(
    text.slice(0, start + START.length) + "\n\n" + table() + "\n\n" + text.slice(end),
    {
      ...(await prettier.resolveConfig(FILE)),
      filepath: FILE,
    },
  )
  if (process.argv.includes("--check")) {
    if (next !== text) {
      console.error(`offline-calls: ${FILE} is out of date; run bun script/offline-calls.ts`)
      process.exit(1)
    }
  } else if (next !== text) {
    await Bun.write(FILE, next)
    console.log(`offline-calls: updated ${FILE}`)
  }
}
